version: "3.7"

services:
  serve:
    image: node:8.12.0-alpine
    #entrypoint: npm install
    #entrypoint: ./node_modules/typescript/bin/tsc
    entrypoint: node ./dist/index_ts.js
    #entrypoint: npm install --save express express-session request-promise pug body-parser
    user: 1000:1000
    volumes:
      - .:/opt/app
    working_dir: /opt/app