version: "3.7"

volumes:
  postgres_data:

services:
  app:
    image: node:12.11.1-alpine
    entrypoint: ["sh", "-c", "npm install && ./node_modules/.bin/tsc && node dist/index.js --env=prod"]
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3
