# https://github.com/grafana/loki/blob/main/production/docker-compose.yaml
# https://grafana.com/docs/loki/latest/installation/docker/
version: "3"

networks:
  standup-slack-bot_default:
    external: true

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - standup-slack-bot_default

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - ./var/log:/opt/app/var/log
      - ./deploy/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - standup-slack-bot_default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - standup-slack-bot_default