version: "3.7"

services:
  serve:
    image: node:8.12.0-alpine
    #entrypoint: npm install
    entrypoint: ./node_modules/typescript/bin/tsc
    user: 1000:1000
    volumes:
      - .:/opt/app
    working_dir: /opt/app