version: "3.7"

services:
  serve:
    image: node:10.15.0-alpine
    entrypoint: ["npm", "run", "start"]
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0.3
