version: "3.7"

services:
  serve:
    image: node:8.12.0-alpine
    #entrypoint: npm install
    #entrypoint: ./node_modules/typescript/bin/tsc
    entrypoint: ["npm", "run", "start"]
    #entrypoint: /bin/sh -c "node ./node_modules/copyfile/app.js -src ./ ./server/**/*.pug ./dist/"
    #entrypoint: npm install --save copyfile
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0.3-alpine
