version: "3.7"

volumes:
  postgres_data:

services:
  server:
    build: &service_app
      dockerfile: deploy/Dockerfile
      context: .
    command: ["server:run", "--env=prod"]
    user: 1000:1000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  standup-notifier:
    <<: *service_app
    command: ["standup:notify", "--env=prod"]
    user: 1000:1000
    depends_on:
      - postgres

  queue-consumer:
    <<: *service_app
    command: ["queue:consume", "--env=prod"]
    user: 1000:1000
    depends_on:
      - postgres

  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 6.0.1-alpine
