version: "3.7"

services:
  serve:
    image: node:14.17.6-alpine
    entrypoint: npm
    command: ["run", "watch"]
    user: 1000:1000
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.2.5-alpine

  openapi-generator:
    image: openapitools/openapi-generator-cli:v5.2.1
    user: "1000"
    volumes:
      - .:/opt/app
    environment:
      JAVA_OPTS: >
        -Dio.swagger.parser.util.RemoteUrl.trustAll=true -Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true
    command: generate -i http://serve:3000/api/doc/swagger.yaml -g typescript-angular -o /opt/app/frontend/src/api/auto -p modelPropertyNaming=original -p ngVersion11.0.0
    working_dir: /opt/app

  tunnel:
    image: jpillora/chisel:latest
    network_mode: host
    command: "client botenza.net:8080 R:3000:3000"
