version: "3.7"

services:
  serve:
    image: node:12.14.1-alpine
    entrypoint: npm
    command: ["run", "start"]
    user: 1000:1000
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.0.1-alpine
