version: "3.7"

volumes:
  postgres_data:

services:
  app:
    image: node:10.15.0-alpine
    entrypoint: ["sh", "-c", "npm install && ./node_modules/.bin/tsc && node dist/index.js"]
    user: 1000:1000
    ports:
      - "443:443"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3
