apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/disks/vol1