CREATE ROLE standup WITH PASSWORD 'standup_123';
CREATE DATABASE standup WITH OWNER "standup";
GRANT ALL PRIVILEGES ON DATABASE standup TO standup;
ALTER DATABASE standup OWNER TO standup;

-- ALTER USER standup WITH PASSWORD 'standup_123';
CREATE DATABASE grafana;

