server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  #- job_name: kubernetes # https://grafana.com/docs/loki/latest/clients/promtail/configuration/#kubernetes_sd_config
  #  kubernetes_sd_config:
  # https://grafana.com/docs/loki/latest/clients/promtail/scraping/#journal-scraping-linux-only
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /opt/app/var/log/*log
    pipeline_stages:
      - json:
         expressions:
           level: level
           timestamp: time
           msg: msg
           requestId: requestId
           userId: userId
      - timestamp:
          source: time
          format: UnixMs
      - labels:
          level: level
          msg: msg
          requestId: requestId
          userId: userId