apiVersion: apps/v1
kind: Deployment
metadata:
  name: standup-api
  labels:
    app: standup-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standup-api
  template:
    metadata:
      labels:
        app: standup-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: create-db
          image: postgres:13.3-alpine
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: service
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          command:
            - "bash"
            - "-c"
            - |
              psql -U postgres -c "CREATE DATABASE standup" || echo "Already exists"
        - name: create-schema
          image: standup-slack-bot:latest
          imagePullPolicy: Never #uncommend if use minikube
          #securityContext:
          #  runAsUser: node
          #  runAsNonRoot: true
          #  runAsGroup: node
          args: [ "database:migrate" ]
          env: &appEnv
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: client-id
            - name: SLACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: secret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: signing-secrent
            - name: DEBUG
              value: "true"
            - name: HOST
              value: "https://standup.botenza.com"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: service
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: service
            - name: DB_DATABASE
              value: standup
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: LOG_DIR
              value: "/var/log"
        - name: fixture-db
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: [ "database:fixture" ]
          env: *appEnv
      containers:
        - name: standup-api
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: ["server:run", "--port=3000", "--env=prod"]
          ports:
            - containerPort: 3000
          env: *appEnv
---
apiVersion: v1
kind: Service
metadata:
  name: standup-api-service
spec:
  selector:
    app: standup-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
