apiVersion: apps/v1
kind: Deployment
metadata:
  name: standup-api
  labels:
    app: standup-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standup-api
  template:
    metadata:
      labels:
        app: standup-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: standup-api
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: ["server:run", "--type=slack-api", "--listen=3000", "--env=dev"]
          ports:
            - containerPort: 3000
          env:
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: client-id
            - name: SLACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: secret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: signing-secrent
            - name: BOT_USER_OAUTH_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: bot-user-oauth-access-token
            - name: DEBUG
              value: "false"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: service
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: service
            - name: DB_DATABASE
              value: standup
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: standup-api-service
spec:
  selector:
    app: standup-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
