apiVersion: apps/v1
kind: Deployment # TODO StatefulSet
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      component: loki
  template:
    metadata:
      labels:
        component: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.3.0
          ports:
            - containerPort: 3100
              name: http
              protocol: TCP
          #args:
          #  - -config.file=/etc/loki/local-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    service: loki-service
spec:
  type: NodePort
  selector:
    component: loki
  ports:
    - port: 3100
      targetPort: 3100