apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  fsGroup: 1000
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgresql-data
              readOnly: false
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres # default
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
      volumes:
        - name: postgresql-data
          hostPath:
            path: "/var/lib/postgresql/data"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      #nodePort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  service: postgres-service

