apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres # default
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      #nodePort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  service: postgres-service

