apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: create-db
          image: postgres:13.1-alpine
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: service
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          command:
            - "bash"
            - "-c"
            - |
              psql -U postgres -c "CREATE DATABASE standup" || echo "Already exists"
        - name: create-schema
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: ["database:migrate"]
          env: &appEnv
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: client-id
            - name: SLACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: secret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: signing-secrent
            - name: BOT_USER_OAUTH_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-api-secret
                  key: bot-user-oauth-access-token
            - name: DEBUG
              value: "true"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: service
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: service
            - name: DB_DATABASE
              value: standup
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
        - name: fixture-db
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: [ "database:fixture"]
          env: *appEnv
      containers:
        - name: ui
          image: standup-slack-bot:latest
          imagePullPolicy: Never
          args: ["server:run", "--type=ui", "--listen=3000", "--env=dev"]
          ports:
            - containerPort: 3000
          env: *appEnv
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
