{{ if eq .Values.certIssuer "selfsigned" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: { }
---
{{ end }}
{{ if eq .Values.certIssuer "letsencrypt" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
{{ end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: standup-bot-cert
spec:
  secretName: standup-bot-cert-secret
  issuerRef:
    kind: Issuer
    name: {{ .Values.certIssuer }}-issuer
  commonName: {{ .Values.domain }}
  dnsNames:
    - {{ .Values.domain }}