apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: standup-bot-ingress
#  {{ if .Values.certIssuer }}
#  annotations:
#    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}-issuer
#  {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: standup-bot-cert-secret
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /api
            pathType: "Prefix"
            backend:
              service:
                name: standup-api-service
                port:
                  number: 3000
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: standup-ui-service
                port:
                  number: 3000