apiVersion: apps/v1
kind: Deployment
metadata:
  name: standup-worker
  labels:
    app: standup-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standup-worker
  template:
    metadata:
      labels:
        app: standup-worker
    spec:
      securityContext:
        {{- include "securityContext" . | indent 9 }}
      volumes:
        - name: standup-worker-log
          hostPath:
            path: "/var/log/standup/worker"
      containers:
        - name: standup-worker
          image: {{ .Values.apiImage }}
          {{- if .Values.imagePullPolicy }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- end }}
          args: ["worker", "--env=prod"]
          volumeMounts:
            - name: standup-worker-log
              mountPath: /opt/app/var/log
              readOnly: false
          env:
            {{- include "env.main" . | indent 12 }}
            {{- include "env.slack" . | indent 12 }}
            {{- include "env.db" . | indent 12 }}
