apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-consumer
  labels:
    app: queue-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: standup-queue-consumer-log
          hostPath:
            path: "/var/log/standup-queue-consumer"
      containers:
        - name: queue-consumer
          image: {{ .Values.apiImage }}
          {{- if .Values.imagePullPolicy }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- end }}
          args: ["queue:consume", "--env=prod"]
          volumeMounts:
            - name: standup-queue-consumer-log
              mountPath: /var/log
              readOnly: false
          env:
            {{- include "env.main" . | indent 12 }}
            {{- include "env.slack" . | indent 12 }}
            {{- include "env.db" . | indent 12 }}
