apiVersion: apps/v1
kind: Deployment
metadata:
  name: standup-ui
  labels:
    app: standup-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standup-ui
  template:
    metadata:
      labels:
        app: standup-ui
    spec:
      containers:
        - name: standup-ui
          image: {{ .Values.uiImage }}
          {{- if .Values.imagePullPolicy }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- end }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: standup-ui-service
spec:
  selector:
    app: standup-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
