/**
 * Standup bot api
 * Standup bot api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sashaaro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StandupAnswers } from './standupAnswers';
import { StandupUser } from './standupUser';


export interface StandupUsers { 
    user?: StandupUser;
    answers?: Array<StandupAnswers>;
}

