/**
 * Standup bot api
 * Standup bot api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sashaaro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Timezone } from './timezone';
import { Channel } from './channel';
import { Question } from './question';


export interface Team { 
    id?: number;
    title?: string;
    isEnabled?: boolean;
    start?: string;
    duration?: number;
    timezone?: Timezone;
    reportChannel?: Channel;
    questions?: Array<Question>;
}

