/**
 * Standup bot api
 * Standup bot api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sashaaro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimezoneUtcOffset } from './timezoneUtcOffset';


export interface Timezone { 
    id?: number;
    name?: number;
    utc_offset?: TimezoneUtcOffset;
}

